version: "3.7"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.20.1-alpine
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./uptime-kuma:/app/data